# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - ytdl-material

on:
  push:
    branches:
      - iamtheantitwink
  workflow_dispatch:

concurrency:
  group: ytdl-material
  cancel-in-progress: true

jobs:
  build:
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: build frontend
        run: |
          cd $GITHUB_WORKSPACE \
          && mkdir ./build \
          && cp ./src ./build/src \
          && cd ./build/src \
          && npm run build --if-present \
          && npm install --prod

      - name: build backend
        run: |
          cd $GITHUB_WORKSPACE \
          && mkdir ./app \
          && cp ./backend ./app \
          && cd ./app \
          && config set strict-ssl false  \
          && npm install --prod 

      - name: copy files
        run: |
          cd $GITHUB_WORKSPACE \
          && cp ./app . \
          && cp ./build/backend/public ./public

      - name: Install yt-dlp, ffmpeg, ffprobe, & twitch downloader
        shell: bash
        run: |
          mkdir ./bin
          chmod +x ./docker-utils/ffmpeg-fetch.sh
          chmod +x ./docker-utils/fetch-twitchdownloader.sh
          ./docker-utils/ffmpeg-fetch.sh
          ./docker-utils/fetch-twitchdownloader.sh

      - name: Remove sensitive files
        run: rm -rf .git .github src chart chrome-extension

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ytdl-material'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0BB543698EEB4659999D1DCBBA182DB5 }}
          package: .
          
